apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hashi-apps
  namespace: argocd
spec:
  description: Project for demo applications
  sourceRepos:
    - 'https://github.com/midhundha/terraform-aws-eks-argocd-vault.git'
    - 'https://helm.releases.hashicorp.com/'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'